# Generated by Django 4.2.7 on 2023-12-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('passport', models.CharField(max_length=9, verbose_name='passport')),
                ('image', models.ImageField(upload_to='passports', verbose_name='imgae')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50, verbose_name='gender')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
