# Generated by Django 4.2.7 on 2023-12-04 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('airplains_number', models.IntegerField(verbose_name='airplains number')),
            ],
            options={
                'verbose_name': 'AirLine',
                'verbose_name_plural': 'AirLines',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('departure', models.CharField(max_length=50, verbose_name='departure')),
                ('arrival', models.CharField(max_length=50, verbose_name='arrival')),
                ('datetime', models.DateTimeField(verbose_name='date')),
                ('seats_number', models.IntegerField(default=50, verbose_name='seats number')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.airline', verbose_name='')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('ticket_class', models.CharField(choices=[('fc', 'first class'), ('bc', 'business class'), ('ec', 'economy class')], max_length=50, verbose_name='class')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.customer', verbose_name='customer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.flight', verbose_name='flight')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
