# Generated by Django 4.2.7 on 2023-12-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_airline_flight_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='seats_number',
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.airline', verbose_name='airline'),
        ),
    ]
