# Generated by Django 4.2.7 on 2023-12-06 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tms', '0004_flight_color_alter_flight_airline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='agent'),
        ),
    ]
