# Generated by Django 4.2.7 on 2023-12-06 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tms', '0005_flight_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='agent',
        ),
        migrations.AddField(
            model_name='ticket',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='agent'),
        ),
    ]
