# Generated by Django 4.2.7 on 2023-11-27 06:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_user_alter_manufacture_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.car_media_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='center',
            field=models.CharField(choices=[('Egypt', 'مصر'), ('Yemen', 'اليمن'), ('Jorden', 'الاردن')], max_length=50, verbose_name='center'),
        ),
    ]
