# Generated by Django 4.2.7 on 2023-11-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_image_alter_manufacture_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='icon')),
                ('title', models.CharField(max_length=50, verbose_name='icon')),
                ('desc', models.TextField(verbose_name='description')),
            ],
        ),
    ]
